---

{{- if .Values.knativeDeploy }}
{{- else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: LoadBalancer # Change here ...
  ports:
  - port: 2180 # Change here ...
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: {{ template "fullname" . }}
{{- end }}
